FROM maven:3.6.3-jdk-11-slim AS base-builder
FROM openjdk:11-jre AS base-runtime

#########################################################

FROM base-builder AS builder
RUN mkdir /opt/app
WORKDIR /opt/app
COPY accounting/pom.xml /opt/app
COPY accounting/lombok.config /opt/app
RUN mvn dependency:go-offline
COPY accounting/src /opt/app/src
RUN mvn package -Dmaven.test.skip

#########################################################

FROM base-runtime AS runtime
RUN mkdir /opt/app
WORKDIR /opt/app
EXPOSE 8080 6565
COPY accounting/run_app_kube.sh /opt/app/run_app_kube.sh
RUN chmod 0755 /opt/app/run_app_kube.sh
COPY --from=builder /opt/app/target/*.jar /opt/app/app.jar
ENTRYPOINT ["/bin/bash", "-c", "/opt/app/run_app_kube.sh"]
